version: "3.7"
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db_turnos'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'flor21'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'flor21'
    ports:
     - "3307:3306"

  node:
    image: node
    working_dir: /var/Frontend/newclient
    environment:
      - PATH=/var/Frontend/node_modules/.bin:$PATH
    ports:
    - 8000:8080
    volumes:
    - .:/var/Frontend
    command:
      npm run serve
