version: "3.7"
services:
  grupo06-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db_turnos'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'flor21'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'flor21'
    ports:
     - "3306:3306"
